[View in Colaboratory](https://colab.research.google.com/github/rajivcusat2003/MyTestRepo/blob/master/TF_intro.ipynb)

In [91]:
import tensorflow as tf
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const_10:0", shape=(), dtype=float32)
Tensor("Const_11:0", shape=(), dtype=float32)
Tensor("add_49:0", shape=(), dtype=float32)


In [92]:
sess = tf.Session()
print(sess.run(total))
print(sess.run({'ab':(a, b), 'total':total}))

7.0
{'ab': (3.0, 4.0), 'total': 7.0}


In [93]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
#print(sess.run(vec))
print(sess.run((out1, out2)))



[0.12019908 0.99476564 0.62069476]
(array([1.3563507, 1.5963343, 1.1196798], dtype=float32), array([2.3563507, 2.5963345, 2.11968  ], dtype=float32))


In [95]:
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.rank(first_primes)))
    v1 = first_primes.eval()
    print(v1)  # will show you your variable.
    

1
[ 2  3  5  7 11]
